openapi: 3.1.0
info:
  title: Partial Withdrawal One-Time API
  version: 1.0.0
  description: API for processing one-time partial withdrawal transactions.
servers:
- url: https://api.your-company-domain.com
  description: Production server
- url: https://sandbox.your-company-domain.com
  description: Sandbox environment
paths:
  /policy/v1/transactions/{cusip}/{policyNumber}/partialwithdrawalonetime:
    post:
      summary: Process a one-time partial withdrawal
      operationId: partialWithdrawalOneTime
      parameters:
      - name: cusip
        in: path
        required: true
        schema:
          type: string
      - name: policyNumber
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                correlationId:
                  type: string
                effectiveDate:
                  type: string
                Object:
                  type: object
                  properties:
                    transactionAmounts:
                      type: object
                    fundAllocation:
                      type: object
                    taxWithholdingInstructions:
                      type: object
                    fundDistributionsArray:
                      type: object
                    payeeOrBeneficiary:
                      type: object
                    address:
                      type: object
                    parties:
                      type: object
                    charges:
                      type: object
                    producer:
                      type: object
                transactionAmounts:
                  type: object
                  properties:
                    requestedAmount:
                      type: number
                    requestedPercentage:
                      type: number
                    amountType:
                      type: string
                    disbursementType:
                      type: string
                    disbursementPaymentForm:
                      type: string
                fundAllocation:
                  type: object
                  properties:
                    allocationOption:
                      type: string
                taxWithholdingInstructions:
                  type: object
                  properties:
                    party:
                      type: object
                    taxWithholdingType:
                      type: string
                    taxRateToUse:
                      type: string
                    filingStatus:
                      type: string
                    dollar:
                      type: number
                    percentage:
                      type: number
                    exemptions:
                      type: object
                    taxJurisdiction:
                      type: string
                taxWithholdingInstructions.party:
                  type: object
                  properties:
                    partyId:
                      type: string
                    firstName:
                      type: string
                    middleName:
                      type: string
                    lastName:
                      type: string
                    organizationName:
                      type: string
                fundDistributionsArray:
                  type: object
                  properties:
                    fundId:
                      type: string
                    fundName:
                      type: string
                    totalFundValue:
                      type: number
                    requestedAmount:
                      type: number
                    fundDistributionSegment:
                      type: object
                fundDistributionsArray.fundDistributionSegment:
                  type: object
                  properties:
                    segmentId:
                      type: string
                    currentAmount:
                      type: number
                    requestedAmount:
                      type: number
                payeeOrBeneficiary:
                  type: object
                  properties:
                    party:
                      type: object
                    paymentForm:
                      type: string
                    allocationPercent:
                      type: number
                    bank:
                      type: object
                payeeOrBeneficiary.party:
                  type: object
                  properties:
                    partyId:
                      type: string
                    firstName:
                      type: string
                    middleName:
                      type: string
                    lastName:
                      type: string
                    organizationName:
                      type: string
                payeeOrBeneficiary.bank:
                  type: object
                  properties:
                    bankId:
                      type: string
                    nameOnAccount:
                      type: string
                    accountStatus:
                      type: string
                    accountType:
                      type: string
                    accountNumber:
                      type: string
                    routingNumber:
                      type: string
                    branchName:
                      type: string
                payeeOrBeneficiary.address:
                  type: object
                  properties:
                    addressId:
                      type: string
                    addressType:
                      type: string
                    addressLine1:
                      type: string
                    addressLine2:
                      type: string
                    addressLine3:
                      type: string
                    city:
                      type: string
                    state:
                      type: string
                    zipCode:
                      type: string
                    zipCodeExtension:
                      type: string
                    country:
                      type: string
                parties:
                  type: object
                  properties:
                    partyRole:
                      type: string
                    partyId:
                      type: string
                    firstName:
                      type: string
                    middleName:
                      type: string
                    lastnName:
                      type: string
                    organizationName:
                      type: string
                    paymentForm:
                      type: string
                    allocationPercentage:
                      type: number
                    forBenefitOfOrForFurtherCredit:
                      type: string
                    bank:
                      type: object
                    address:
                      type: object
                parties.bank:
                  type: object
                  properties:
                    bankId:
                      type: string
                    nameOnAccount:
                      type: string
                    accountStatus:
                      type: string
                    accountType:
                      type: string
                    accountNumber:
                      type: string
                    routingNumber:
                      type: string
                    branchName:
                      type: string
                parties.address:
                  type: object
                  properties:
                    addressId:
                      type: string
                    addressType:
                      type: string
                    addressLine1:
                      type: string
                    addressLine2:
                      type: string
                    addressLine3:
                      type: string
                    city:
                      type: string
                    state:
                      type: string
                    zipCode:
                      type: string
                    zipCodeExtension:
                      type: string
                    country:
                      type: string
                charges:
                  type: object
                  properties:
                    chargeType:
                      type: string
                    chargeWaiverIndicator:
                      type: string
                    chargeWaiverReason:
                      type: string
                overrideBoolean:
                  type: boolean
                producer:
                  type: object
                  properties:
                    producerNumber:
                      type: string
                    npn:
                      type: string
                    crdNumber:
                      type: string
                associatedFirmId:
                  type: string
                NSCCparticipantID:
                  type: string
              required:
              - correlationId
              - effectiveDate
              - requestedAmount
              - requestedPercentage
              - amountType
              - disbursementType
              - allocationOption
              - partyId
              - taxWithholdingType
              - taxRateToUse
              - partyId
              - paymentForm
              - allocationPercentage
            example:
              correlationId: 123e4567-e89b-12d3-a456-426614174000
              effectiveDate: '2023-03-06'
              transactionAmounts:
                requestedAmount: 1000.0
                amountType: AMOUNT
                disbursementType: GROSS
                disbursementPaymentForm: DTCC
              fundAllocation:
                allocationOption: PRORATA
      responses:
        '200':
          description: Successful transaction
          content:
            application/json:
              schema:
                type: object
              example:
                status: success
                transactionId: TX123456
